# Generated by Django 4.2 on 2023-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negPosAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(blank=True, choices=[('Positive', 'positive'), ('Negative', 'negative'), ('Neutral', 'neutral')], max_length=10, null=True),
        ),
    ]
