# Generated by Django 4.2 on 2023-04-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negPosAPI', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
